# ==================
# Environment
# ==================
environment: production

# ==================
# Base
# ==================
url: "https://pusher.github.io/chameleon-docs"

# Build settings

assets:
  baseurl: https://pusher.github.io/chameleon-docs
  cachebust: hard
  debug: false
  css_compressor: sass
  js_compressor: uglifier