# ==================
# Environment
# ==================
environment: development

# Site settings
title: Pusher Chameleon
gitrepo: https://github.com/pusher/chameleon
version: 0.1.9

# Build settings
markdown: kramdown

gems: [jekyll-assets, rouge, autoprefixer-rails, kramdown]

exclude: [
  "Gemfile",
  "Gemfile.lock",
  "Rakefile"
]

kramdown:
    input: GFM
    syntax_highlighter: rouge
    css_class: highlight

highlighter:
    options: ['startinline']

assets:
  baseurl: http://127.0.0.1:4000/
  cache: false
  cachebust: none
  css_compressor: sass
  js_compressor: uglifier
  debug: true