# ==================
# Environment
# ==================
environment: development

# Site settings
title: Pusher Chameleon
gitrepo: https://github.com/pusher/chameleon

# Build settings
markdown: kramdown

gems: [jekyll-assets, rouge, autoprefixer-rails, kramdown, octopress-autoprefixer]

exclude: [
  "Gemfile",
  "Gemfile.lock",
  "Rakefile"
]

kramdown:
  input: GFM
  syntax_highlighter: rouge

highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'

assets:
  baseurl: http://127.0.0.1:4000/
  cache: false
  cachebust: none
  css_compressor: sass
  js_compressor: uglifier
  debug: true